name: laeqa
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - pip
  - numpy~=1.26
  - scipy
  - matplotlib        
  - imageio
  - ffmpeg            
  - pillow
  - opencv            
  - ipykernel

  - pip:
      - torch==2.2.2
      - triton==2.2.0
      - transformers==4.39.3
      - accelerate==0.29.3
      - safetensors
      - tokenizers==0.15.2
      - tqdm==4.66.2
      - natsort==8.4.0
      - bitsandbytes==0.43.1
      - openai==1.3.7
      - tenacity==8.2.3
      - imageio==2.34.0
      - pypng==0.20220715.0
      - regex
      - opencv-python==4.9.0.80
